In [1]:
import numpy as np
import pandas as pd
string_data = pd.Series([ 'aardvark', 'artichoke', np.nan, 'avocado' ])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [2]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [3]:
string_data.dropna()

0     aardvark
1    artichoke
3      avocado
dtype: object

In [4]:
string_data[ string_data.notnull() ]

0     aardvark
1    artichoke
3      avocado
dtype: object

In [5]:
NA = np.nan
data = pd.DataFrame([ [ 1., 6.5, 3., NA ], [ 1., NA, NA ], [ NA, NA, NA ], [ NA, 6.5, 3., NA ] ])
clean = data.dropna()
data

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [6]:
clean

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [7]:
data.dropna(how='all')

0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [8]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.439456       NaN       NaN
1  0.963770       NaN       NaN
2  1.666601       NaN  0.347230
3 -0.116106       NaN  0.367567
4  1.321469 -0.197646 -0.887657
5 -0.463053  0.070930  0.742509
6 -0.212017  0.014305  0.277173

In [9]:
df.dropna()

0         1         2
4  1.321469 -0.197646 -0.887657
5 -0.463053  0.070930  0.742509
6 -0.212017  0.014305  0.277173

In [10]:
df.dropna(thresh=2)

0         1         2
2  1.666601       NaN  0.347230
3 -0.116106       NaN  0.367567
4  1.321469 -0.197646 -0.887657
5 -0.463053  0.070930  0.742509
6 -0.212017  0.014305  0.277173

In [11]:
df.fillna(0)

0         1         2
0 -0.439456  0.000000  0.000000
1  0.963770  0.000000  0.000000
2  1.666601  0.000000  0.347230
3 -0.116106  0.000000  0.367567
4  1.321469 -0.197646 -0.887657
5 -0.463053  0.070930  0.742509
6 -0.212017  0.014305  0.277173

In [12]:
data2 = pd.Series([ 1., NA, 3.5, NA, 7 ])
data2.fillna(data2.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [13]:
data = pd.DataFrame({ 'k1': [ 'one', 'two' ] * 3 + [ 'two' ], 'k2': [ 1, 1, 2, 3, 3, 4, 4 ] })
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [14]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [15]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [16]:
data['v1'] = range(7)
data.drop_duplicates([ 'k1' ])

k1  k2  v1
0  one   1   0
1  two   1   1

In [17]:
data.drop_duplicates([ 'k1', 'k2' ], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [25]:
data = pd.DataFrame({ 'food': [ 'bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'novalox' ] , 'ounces': [ 4, 3, 12, 6, 7.5, 8, 3, 5, 6 ] })
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8      novalox     6.0

In [20]:
meat_to_animal = { 'bacon': 'pig', 'pulled pork': 'pig', 'pastrami': 'cow', 'corned beef': 'cow', 'honey ham': 'pig', 'novalox': 'salmon' }

In [21]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5         beacon
6       pastrami
7      honey ham
8        novalox
Name: food, dtype: object

In [23]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5       Beacon     8.0     NaN
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8      novalox     6.0  salmon

In [26]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [27]:
data = pd.Series([ 1, -999, 2, -999, -1000, 3 ])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [28]:
data.replace(-999, NA)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [29]:
data.replace([ -999, -1000 ], NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [30]:
data.replace([ -999, -1000 ], [ NA, 0 ])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [32]:
data = pd.DataFrame(np.arange(12).reshape(( 3, 4 )), index=[ 'Ohio', 'Colorado', 'New York' ], columns=[ 'one', 'two', 'three', 'four' ])
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [33]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [34]:
data.rename(index={ 'OHIO': 'INDIANA' }, columns={ 'three': 'peekaboo' })

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [35]:
data.rename(index={ 'OHIO': 'INDIANA' }, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [36]:
ages = [ 20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32 ]
bins = [ 18, 25, 35, 60, 100 ]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [38]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [39]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [40]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [41]:
pd.cut(ages, [ 18, 26, 36, 61, 100 ], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [42]:
group_names = [ 'Youth', 'YouthAdult', 'MiddleAged', 'Senior' ]
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YouthAdult, Youth, ..., YouthAdult, Senior, MiddleAged, MiddleAged, YouthAdult]
Length: 12
Categories (4, object): [Youth < YouthAdult < MiddleAged < Senior]

In [43]:
data1 = np.random.randn(20)
pd.cut(data1, 4, precision=2)

[(-1.41, -0.61], (-1.41, -0.61], (-1.41, -0.61], (-0.61, 0.19], (0.19, 1.0], ..., (1.0, 1.8], (0.19, 1.0], (0.19, 1.0], (1.0, 1.8], (-0.61, 0.19]]
Length: 20
Categories (4, interval[float64]): [(-1.41, -0.61] < (-0.61, 0.19] < (0.19, 1.0] < (1.0, 1.8]]

In [44]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats

[(0.634, 3.361], (-3.735, -0.747], (-0.747, -0.056], (0.634, 3.361], (-0.747, -0.056], ..., (-3.735, -0.747], (0.634, 3.361], (-3.735, -0.747], (0.634, 3.361], (-0.056, 0.634]]
Length: 1000
Categories (4, interval[float64]): [(-3.735, -0.747] < (-0.747, -0.056] < (-0.056, 0.634] < (0.634, 3.361]]

In [45]:
pd.value_counts(cats)

(0.634, 3.361]      250
(-0.056, 0.634]     250
(-0.747, -0.056]    250
(-3.735, -0.747]    250
dtype: int64

In [46]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.007596    -0.033997    -0.042139     0.040281
std       0.993780     1.002033     0.979152     1.003913
min      -3.298806    -3.174960    -3.178460    -3.146749
25%      -0.678224    -0.721002    -0.664201    -0.651090
50%       0.017140    -0.005571    -0.024196     0.047300
75%       0.655337     0.643030     0.582750     0.714251
max       2.994104     2.644773     4.023516     3.286093

In [47]:
col = data[2]
col[np.abs(col) > 3]

101    4.023516
508   -3.002716
818   -3.164653
891   -3.178460
Name: 2, dtype: float64

In [48]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
101 -0.605512  0.330279  4.023516 -1.144686
142 -0.204501 -0.348346  1.328387 -3.146749
211 -3.298806 -0.419696 -0.054337 -1.127148
248 -1.131999 -3.174960 -0.222223  1.183309
488 -3.218232  0.741181  1.225011  1.483236
508  0.799361  1.469207 -3.002716 -0.534530
520  0.044148 -1.783457  0.506837  3.286093
752 -0.187179 -0.333205  0.453961 -3.003057
756  1.293004 -1.767113 -0.955497  3.072921
793  0.747592 -0.182721 -0.246060  3.024336
818 -0.705115  0.509537 -3.164653  1.346685
886 -3.170404 -0.339314 -0.936691 -1.007437
891 -0.060483 -1.052602 -3.178460 -1.119482

In [49]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.006908    -0.033822    -0.042816     0.040047
std       0.991622     1.001500     0.974345     1.002271
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.678224    -0.721002    -0.664201    -0.651090
50%       0.017140    -0.005571    -0.024196     0.047300
75%       0.655337     0.643030     0.582750     0.714251
max       2.994104     2.644773     3.000000     3.000000

In [50]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0 -1.0 -1.0  1.0
3  1.0  1.0 -1.0  1.0
4 -1.0  1.0  1.0  1.0

In [52]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([0, 1, 3, 2, 4])

In [53]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [54]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [55]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [56]:
choices = pd.Series([ 5, 6, -1, 4, 7 ])
draws = choices.sample(n=10, replace=True)
draws

4    7
0    5
0    5
3    4
4    7
2   -1
0    5
1    6
3    4
3    4
dtype: int64

In [57]:
df = pd.DataFrame({ 'key': [ 'b', 'b', 'a', 'c', 'a', 'b' ], 'data1': range(6) })
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [58]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [59]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_and_dummy = df[[ 'data1' ]].join(dummies)
df_and_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [60]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [61]:
pieces = [ x.strip() for x in val.split(',') ]
pieces

['a', 'b', 'guido']

In [62]:
'::'.join(pieces)

'a::b::guido'

In [63]:
'a' in val

True

In [64]:
val.index(',')

1

In [65]:
val.find(':')

-1

In [66]:
val.index(':')

ValueError: substring not found

In [67]:
val.count(',')

2

In [68]:
val.replace(',', '::')

'a::b:: guido'

In [69]:
val.replace(',', '')

'ab guido'

In [70]:
import re
text = 'foo bar\t baz \tqux'
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [71]:
regex = re.compile('\s+')
regex.findall(text)

[' ', '\t ', ' \t']

In [72]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern,flags = re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [74]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [75]:
text[m.start():m.end()]

'dave@google.com'

In [76]:
print(regex.match(text))

None


In [77]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [78]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern,flags=re.IGNORECASE)
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [79]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [80]:
data = {'Dave': 'dave@google.com', 'Steve':'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [81]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [82]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [83]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [84]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [85]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [86]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [87]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [88]:
data = pd.Series(np.random.randn(9),index=[['a', 'a', 'a', 'b', 'b', 'c', 'c','d', 'd'],[1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -0.639552
   2    0.956416
   3    0.911154
b  1    0.619817
   3    0.025121
c  1   -0.341318
   2    0.200594
d  2    0.638058
   3    0.627571
dtype: float64

In [89]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 2, 0, 1, 1, 2]])

In [90]:
data['b']

1    0.619817
3    0.025121
dtype: float64

In [91]:
data['b':'c']

b  1    0.619817
   3    0.025121
c  1   -0.341318
   2    0.200594
dtype: float64

In [92]:
data.loc[:, 2]

a    0.956416
c    0.200594
d    0.638058
dtype: float64

In [93]:
data.unstack()

1         2         3
a -0.639552  0.956416  0.911154
b  0.619817       NaN  0.025121
c -0.341318  0.200594       NaN
d       NaN  0.638058  0.627571

In [94]:
data.unstack().stack()

a  1   -0.639552
   2    0.956416
   3    0.911154
b  1    0.619817
   3    0.025121
c  1   -0.341318
   2    0.200594
d  2    0.638058
   3    0.627571
dtype: float64

In [95]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),index=[['a', 'a', 'b', 'b'], [1, 2, 1,2]],columns=[['Ohio', 'Ohio', 'Colorado'],
                    ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [96]:
frame.index.names = [ 'k1', 'k2' ]
frame.columns.names = [ 'state', 'color' ]
frame

state  Ohio     Colorado
color Green Red    Green
k1 k2                   
a  1      0   1        2
   2      3   4        5
b  1      6   7        8
   2      9  10       11

In [97]:
frame['Ohio']

color  Green  Red
k1 k2            
a  1       0    1
   2       3    4
b  1       6    7
   2       9   10

In [98]:
frame.swaplevel('k1', 'k2')

state  Ohio     Colorado
color Green Red    Green
k2 k1                   
1  a      0   1        2
2  a      3   4        5
1  b      6   7        8
2  b      9  10       11

In [99]:
frame.sort_index(level=1)

state  Ohio     Colorado
color Green Red    Green
k1 k2                   
a  1      0   1        2
b  1      6   7        8
a  2      3   4        5
b  2      9  10       11

In [100]:
frame.swaplevel(0, 1).sort_index(level=1)

state  Ohio     Colorado
color Green Red    Green
k2 k1                   
1  a      0   1        2
2  a      3   4        5
1  b      6   7        8
2  b      9  10       11

In [101]:
frame.sum(level='k2')

state  Ohio     Colorado
color Green Red    Green
k2                      
1         6   8       10
2        12  14       16

In [102]:
frame.sum(level='color', axis=1)

color  Green  Red
k1 k2            
a  1       2    1
   2       8    4
b  1      14    7
   2      20   10

In [103]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1), 'c': ['one', 'one', 'one', 'two','two', 'two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [104]:
frame2 = frame.set_index([ 'c', 'd' ])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [105]:
frame.set_index([ 'c', 'd' ], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [106]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [107]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a','b'], 'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [108]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [109]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [110]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [112]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a','b'],'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})

In [113]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [114]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [115]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [116]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [117]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]},index=['a','b'])

In [118]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [119]:
right1

group_val
a        3.5
b        7.0

In [120]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [121]:
arr = np.arange(12).reshape(( 3, 4 ))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.concatenate([ arr, arr ], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [123]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

In [124]:
pd.concat([ s1, s2, s3 ])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [125]:
pd.concat([ s1, s2, s3 ], axis=1, sort=False)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [126]:
s4 = pd.concat([ s1, s3 ])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [128]:
pd.concat([ s1, s4 ], axis=1, sort=False)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [129]:
pd.concat([ s1, s4 ], axis=1, join='inner')

0  1
a  0  0
b  1  1

In [130]:
pd.concat([ s1, s4 ], axis=1, join_axes=[ [ 'a', 'c', 'b', 'e' ] ])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  1.0
e  NaN  NaN

In [131]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],index=['f', 'e', 'd', 'c', 'b', 'a'])
b = pd.Series(np.arange(len(a), dtype=np.float64),index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1] = NA

In [132]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [133]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [135]:
np.where(pd.isnull(b), b, a)

array([nan, 2.5, nan, 3.5, 4.5, nan])

In [136]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [137]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),index=pd.Index(['Ohio','Colorado'],name='state'),
                    columns=pd.Index(['one', 'two','three'],name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [138]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [139]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [140]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [141]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],'A': [1, 2, 3],'B': [4, 5, 6],'C': [7, 8, 9]})
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [142]:
melted = pd.melt(df, [ 'key' ])
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [143]:
reshaped = melted.pivot('key', 'variable', 'value')
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [144]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [145]:
pd.melt(df, value_vars=[ 'key', 'A', 'B' ])

variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6

In [146]:
pd.melt(df, id_vars=[ 'key' ], value_vars=[ 'A', 'B' ])

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6