In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np

In [4]:
obj = Series([4,7,-5,3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4,7,-5,3],index=['d','b','a','c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2[['a','b','c']]

a   -5
b    7
c    3
dtype: int64

In [13]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [14]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
adata = {'ohio':35000,'texas':71000,'oregon':16000,'uthah':5000}

In [19]:
obj3 = Series(adata)

In [20]:
obj3

ohio      35000
texas     71000
oregon    16000
uthah      5000
dtype: int64

In [21]:
states = ['california','ohio','oregon','texas']

In [22]:
obj4 = Series(adata,index=states)

In [23]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

california     True
ohio          False
oregon        False
texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

california    False
ohio           True
oregon         True
texas          True
dtype: bool

In [26]:
obj4.isnull()

california     True
ohio          False
oregon        False
texas         False
dtype: bool

In [27]:
obj3

ohio      35000
texas     71000
oregon    16000
uthah      5000
dtype: int64

In [28]:
obj4

california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
dtype: float64

In [29]:
obj3+obj4

california         NaN
ohio           70000.0
oregon         32000.0
texas         142000.0
uthah              NaN
dtype: float64

In [30]:
obj4.name ='population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
california        NaN
ohio          35000.0
oregon        16000.0
texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['bob','steve','jeff','ryan']

In [35]:
obj

bob      4
steve    7
jeff    -5
ryan     3
dtype: int64

- DataFrame

In [36]:
data = {'state':['ohio','ohio','ohio','nevada','nevada','nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [37]:
frame= DataFrame(data)

In [38]:
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5  nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [40]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  nevada  2.4
4  2002  nevada  2.9
5  2003  nevada  3.2

In [41]:
frame2 = DataFrame(data,columns=['year','state','pop','debt'],
                     index = ['one','two','three','four','five','six'])

In [42]:
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  nevada  2.4  NaN
five   2002  nevada  2.9  NaN
six    2003  nevada  3.2  NaN

In [43]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     nevada
five     nevada
six      nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [45]:
frame2.loc['three']

year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    ohio  1.5  16.5
two    2001    ohio  1.7  16.5
three  2002    ohio  3.6  16.5
four   2001  nevada  2.4  16.5
five   2002  nevada  2.9  16.5
six    2003  nevada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6.)

In [49]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   0.0
two    2001    ohio  1.7   1.0
three  2002    ohio  3.6   2.0
four   2001  nevada  2.4   3.0
five   2002  nevada  2.9   4.0
six    2003  nevada  3.2   5.0

In [50]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [51]:
frame2['debt'] = val

In [52]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [53]:
frame2['eastern'] = frame2.state =='ohio'

In [54]:
frame2

year   state  pop  debt  eastern
one    2000    ohio  1.5   NaN     True
two    2001    ohio  1.7  -1.2     True
three  2002    ohio  3.6   NaN     True
four   2001  nevada  2.4  -1.5    False
five   2002  nevada  2.9  -1.7    False
six    2003  nevada  3.2   NaN    False

In [55]:
del frame2['eastern']

In [56]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  nevada  2.4  -1.5
five   2002  nevada  2.9  -1.7
six    2003  nevada  3.2   NaN

In [57]:
pop = {'nevada':{2001:2.4,2002:2.9},
      'ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [58]:
frame3= DataFrame(pop)

In [59]:
frame3

nevada  ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [60]:
frame3.T

2000  2001  2002
nevada   NaN   2.4   2.9
ohio     1.5   1.7   3.6

In [61]:
DataFrame(pop,index=[2001,2002,2003])

AttributeError: 'list' object has no attribute 'astype'

In [ ]:
pdata = {'ohio':frame3['ohio'][:-1],
        'nevada':frame3['nevada'][:2]}

In [ ]:
DataFrame(pdata)

In [62]:
frame3.index.name = 'year';frame3.columns.name = 'state'

In [63]:
frame3

state  nevada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [64]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [65]:
frame2.values

array([[2000, 'ohio', 1.5, nan],
       [2001, 'ohio', 1.7, -1.2],
       [2002, 'ohio', 3.6, nan],
       [2001, 'nevada', 2.4, -1.5],
       [2002, 'nevada', 2.9, -1.7],
       [2003, 'nevada', 3.2, nan]], dtype=object)

In [66]:
obj = Series(range(3),index=['a','b','c'])

In [67]:
index= obj.index

In [68]:
index

Index(['a', 'b', 'c'], dtype='object')

In [69]:
index[1:]

Index(['b', 'c'], dtype='object')

In [70]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [71]:
labels = pd.Index(np.arange(3))

In [72]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [73]:
obj2= Series([1.5,-2.5,0],index = labels)

In [74]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [75]:
obj2.index is labels

True

In [76]:
frame3

state  nevada  ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [77]:
frame3.columns

Index(['nevada', 'ohio'], dtype='object', name='state')

In [78]:
'ohio' in frame3.columns

True

In [79]:
2003 in frame3.index

False

In [80]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [81]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [82]:
obj = Series([4.5,7.5,-5.3,3.6],index=['d','b','a','c'])

In [83]:
obj

d    4.5
b    7.5
a   -5.3
c    3.6
dtype: float64

In [84]:
obj2 = obj.reindex(list('abcde'))

In [85]:
obj2

a   -5.3
b    7.5
c    3.6
d    4.5
e    NaN
dtype: float64

In [86]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [87]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [88]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [89]:
frame=  DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','b','c'],
                    columns=['ohio','texas','california'])

In [90]:
frame

ohio  texas  california
a     0      1           2
b     3      4           5
c     6      7           8

In [91]:
frame2 = frame.reindex(['a','b','c','d'])

In [92]:
frame2

ohio  texas  california
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [93]:
states = ['texas','utah','california']

In [94]:
frame.reindex(columns = states)

texas  utah  california
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [95]:
frame.loc[['a','b','c','d'],states]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


texas  utah  california
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    7.0   NaN         8.0
d    NaN   NaN         NaN

In [96]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [97]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [98]:
new_obj = obj.drop('c')

In [99]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [100]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [101]:
data= DataFrame(np.arange(16.).reshape((4,4)),index=['ohio','colorado','utah','new york'],
                  columns=['one','two','three','four'])

In [102]:
data

one   two  three  four
ohio       0.0   1.0    2.0   3.0
colorado   4.0   5.0    6.0   7.0
utah       8.0   9.0   10.0  11.0
new york  12.0  13.0   14.0  15.0

In [103]:
data.drop(['colorado','ohio'])

one   two  three  four
utah       8.0   9.0   10.0  11.0
new york  12.0  13.0   14.0  15.0

In [104]:
data.drop('two',axis=1)

one  three  four
ohio       0.0    2.0   3.0
colorado   4.0    6.0   7.0
utah       8.0   10.0  11.0
new york  12.0   14.0  15.0

In [105]:
data.drop(['two','four'],axis='columns')

one  three
ohio       0.0    2.0
colorado   4.0    6.0
utah       8.0   10.0
new york  12.0   14.0

In [106]:
obj.drop('c',inplace=True)

In [107]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [108]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [109]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [110]:
obj['b']

1.0

In [111]:
obj[1]

1.0

In [112]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [113]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [114]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [115]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [116]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [117]:
obj['b':'c']=5

In [118]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [119]:
data= DataFrame(np.arange(16.).reshape((4,4)),index=['ohio','colorado','utah','new york'],
                  columns=['one','two','three','four'])

In [120]:
data

one   two  three  four
ohio       0.0   1.0    2.0   3.0
colorado   4.0   5.0    6.0   7.0
utah       8.0   9.0   10.0  11.0
new york  12.0  13.0   14.0  15.0

In [121]:
data['two']

ohio         1.0
colorado     5.0
utah         9.0
new york    13.0
Name: two, dtype: float64

In [122]:
data[['three','one']]

three   one
ohio        2.0   0.0
colorado    6.0   4.0
utah       10.0   8.0
new york   14.0  12.0

In [123]:
data[:2]

one  two  three  four
ohio      0.0  1.0    2.0   3.0
colorado  4.0  5.0    6.0   7.0

In [124]:
data[data['three']>5]

one   two  three  four
colorado   4.0   5.0    6.0   7.0
utah       8.0   9.0   10.0  11.0
new york  12.0  13.0   14.0  15.0

In [125]:
data <5

one    two  three   four
ohio       True   True   True   True
colorado   True  False  False  False
utah      False  False  False  False
new york  False  False  False  False

In [126]:
data[data<5]=0

In [127]:
data

one   two  three  four
ohio       0.0   0.0    0.0   0.0
colorado   0.0   5.0    6.0   7.0
utah       8.0   9.0   10.0  11.0
new york  12.0  13.0   14.0  15.0

In [128]:
data.loc['colorado',['two','three']]

two      5.0
three    6.0
Name: colorado, dtype: float64

In [129]:
data.iloc[2,[3,0,1]]

four    11.0
one      8.0
two      9.0
Name: utah, dtype: float64

In [130]:
data.iloc[2]

one       8.0
two       9.0
three    10.0
four     11.0
Name: utah, dtype: float64

In [131]:
data.iloc[[1,2],[3,0,1]]

four  one  two
colorado   7.0  0.0  5.0
utah      11.0  8.0  9.0

In [132]:
data.loc[:'utah','two']

ohio        0.0
colorado    5.0
utah        9.0
Name: two, dtype: float64

In [133]:
data.iloc[:,:3][data.three>5]

one   two  three
colorado   0.0   5.0    6.0
utah       8.0   9.0   10.0
new york  12.0  13.0   14.0

In [134]:
ser  = Series(np.arange(3.))

In [135]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [136]:
ser2 =Series(np.arange(3.),index=['a','b','c'])

In [137]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [138]:
ser2[-1]

2.0

In [139]:
ser[:1]

0    0.0
dtype: float64

In [140]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [141]:
ser.iloc[:1]

0    0.0
dtype: float64

In [142]:
s1 = Series([7.2,-2.5,3.4,1.5],index=['a','c','d','e'])

In [143]:
s2 = Series([-2.1,3.6,3.4,4,1.5],index=['a','c','e','f','g'])

In [144]:
s1

a    7.2
c   -2.5
d    3.4
e    1.5
dtype: float64

In [145]:
s2

a   -2.1
c    3.6
e    3.4
f    4.0
g    1.5
dtype: float64

In [146]:
s1+s2

a    5.1
c    1.1
d    NaN
e    4.9
f    NaN
g    NaN
dtype: float64

In [147]:
df1 = DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['ohio','texas','oregon'])

In [148]:
df1

b    c    d
ohio    0.0  1.0  2.0
texas   3.0  4.0  5.0
oregon  6.0  7.0  8.0

In [149]:
df2 = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bcd'),index=['utah','ohio','texas','oregon'])

In [150]:
df2

b     c     d
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [151]:
df1+df2

b     c     d
ohio     3.0   5.0   7.0
oregon  15.0  17.0  19.0
texas    9.0  11.0  13.0
utah     NaN   NaN   NaN

In [152]:
df1 = DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [153]:
df2 = DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [154]:
df2.loc[1,'b'] = np.nan

In [155]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [156]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [157]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [158]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [159]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [160]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [161]:
arr = np.arange(12.).reshape((3,4))

In [162]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [163]:
arr[0]

array([0., 1., 2., 3.])

In [164]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [165]:
frame = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bcd'),index=['utah','ohio','texas','oregon'])

In [166]:
series = frame.iloc[0]

In [167]:
frame

b     c     d
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [168]:
series

b    0.0
c    1.0
d    2.0
Name: utah, dtype: float64

In [169]:
frame - series

b    c    d
utah    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
oregon  9.0  9.0  9.0

In [170]:
series2 = Series(range(3),index=[list('bef')])

In [171]:
series2

b    0
e    1
f    2
dtype: int64

In [172]:
series3 = frame['d']

In [173]:
frame

b     c     d
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [174]:
series2

b    0
e    1
f    2
dtype: int64

In [175]:
frame.sub(series3,axis='index')

b    c    d
utah   -2.0 -1.0  0.0
ohio   -2.0 -1.0  0.0
texas  -2.0 -1.0  0.0
oregon -2.0 -1.0  0.0

In [176]:
frame = DataFrame(np.random.randn(4,3),columns=list('bde'),index=['utah','ohio','texas','oregon'])

In [177]:
frame

b         d         e
utah    0.356927  0.085175 -0.455751
ohio    1.508961  0.992273 -0.133266
texas   0.540064  1.202785 -2.293819
oregon  1.185636  0.294228  1.232250

In [178]:
np.abs(frame)

b         d         e
utah    0.356927  0.085175  0.455751
ohio    1.508961  0.992273  0.133266
texas   0.540064  1.202785  2.293819
oregon  1.185636  0.294228  1.232250

In [179]:
f = lambda x:x.max() - x.min()

In [180]:
frame.apply(f)

b    1.152034
d    1.117610
e    3.526069
dtype: float64

In [181]:
frame.apply(f,axis=1)

utah      0.812678
ohio      1.642227
texas     3.496604
oregon    0.938022
dtype: float64

In [182]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [183]:
frame.apply(f)

b         d         e
min  0.356927  0.085175 -2.293819
max  1.508961  1.202785  1.232250

In [184]:
format1 = lambda x:'%.2f' %x

In [185]:
frame.applymap(format1)

b     d      e
utah    0.36  0.09  -0.46
ohio    1.51  0.99  -0.13
texas   0.54  1.20  -2.29
oregon  1.19  0.29   1.23

In [186]:
frame['e'].map(format1)

utah      -0.46
ohio      -0.13
texas     -2.29
oregon     1.23
Name: e, dtype: object

In [187]:
obj = Series(range(4),index=['d','a','b','c'])

In [188]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [189]:
frame = DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

In [190]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [191]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [192]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [193]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [194]:
obj = Series([4,7,-3,2])

In [195]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [196]:
obj = Series([4,np.nan,7,np.nan,-3,2])

In [197]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [198]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [199]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [200]:
frame.sort_values(by ='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [201]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [202]:
obj= Series([7,-5,7,4,2,0,4])

In [203]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [204]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [205]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [206]:
frame = DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [207]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [208]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [209]:
obj = Series(range(5),index=['a','a','b','b','c'])

In [210]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [211]:
obj.index.is_unique

False

In [212]:
obj['a']

a    0
a    1
dtype: int64

In [213]:
obj['c']

4

In [214]:
df = DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [215]:
df

0         1         2
a -0.428994 -0.063039  1.673011
a  2.013948 -0.935172 -0.148307
b -1.507722  0.034879 -1.777984
b -0.302180 -0.223479 -1.440601

In [216]:
df.loc['b']

0         1         2
b -1.507722  0.034879 -1.777984
b -0.302180 -0.223479 -1.440601

In [217]:
df = DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                 index=['a','b','c','d'],
                 columns=['one','two'])

In [218]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [219]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [220]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [221]:
df.mean(axis=1,skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [222]:
df.idxmax()

one    b
two    d
dtype: object

In [223]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [224]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [225]:
obj = Series(['a','a','b','c']*4)

In [226]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [240]:
obj  = Series(['a','c','d','a','a','b','b','c','c'])

In [241]:
uniques = obj.unique()

In [242]:
uniques

array(['a', 'c', 'd', 'b'], dtype=object)

In [243]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [244]:
pd.value_counts(obj.values,sort=False)

a    3
c    3
b    2
d    1
dtype: int64

In [245]:
obj

0    a
1    c
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [246]:
mask =obj.isin(['b','c'])

In [247]:
obj[mask]

1    c
5    b
6    b
7    c
8    c
dtype: object

In [248]:
to_match= Series(['c','a','b','b','c','a'])

In [249]:
uniques = Series(['c','b','a'])

In [250]:
pd.Index(uniques).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [251]:
data =DataFrame({'qu1':[1,3,4,3,4],
                   'qu2':[2,3,1,2,3],
                   'qu3':[1,5,2,4,4]})

In [252]:
result = data.apply(pd.value_counts).fillna(0)

In [253]:
result

qu1  qu2  qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [264]:
pd.options.display.max_rows = 10

In [266]:
data.to_csv('save_name')

In [274]:
import sqlite3

In [275]:
query ="""
create table test
(a varchar(20),b varchar(20),
c real, d integer
);"""

In [276]:
con =sqlite3.connect('mydata.sqlite')

In [277]:
con.execute(query)